SELECT
    RESIDENT_STATE,
    COUNT(*) AS Total_Recorded_Cases,
    NULLIF(COUNT(CASE WHEN HOSPITALIZATION_YN = 'Yes' THEN 1 END), 0) AS Hospitalization_Count,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) AS Death_Count,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) * 100.0 / COUNT(*) AS Deaths_Per_Case_Pct,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) * 100.0 / NULLIF(COUNT(CASE WHEN HOSPITALIZATION_YN = 'Yes' THEN 1 END), 0) AS Deaths_Per_Hospitalization_Pct
FROM {{ ref('stg_cdc_cases') }}
GROUP BY RESIDENT_STATE