SELECT
    RESIDENT_STATE,
    COUNT(*) AS Total_Recorded_Cases,
    NULLIF(COUNT(CASE WHEN HOSPITALIZATION_YN = 'Yes' THEN 1 END), 0) AS Hospitalization_Count,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) AS Death_Count,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) * 1.0 / COUNT(*) AS DEATHS_PER_CASE,
    NULLIF(COUNT(CASE WHEN DEATH_YN = 'Yes' THEN 1 END), 0) * 1.0 / NULLIF(COUNT(CASE WHEN HOSPITALIZATION_YN = 'Yes' THEN 1 END), 0) AS DEATHS_PER_HOSPITALIZATION
FROM {{ ref('stg_cdc_cases') }}
GROUP BY RESIDENT_STATE
ORDER BY DEATHS_PER_CASE DESC