SELECT
    CAST(NULLIF(TRIM("case_month"), '') || '-01' AS DATE) AS Case_Month,
    NULLIF(TRIM("res_state"), '') AS Resident_State,
    TRY_CAST(NULLIF(TRIM("state_fips_code"), '') AS INT) AS State_FIPS,
    NULLIF(TRIM("res_county"), '') AS Resident_County,
    TRY_CAST(NULLIF(TRIM("county_fips_code"), '') AS INT) AS County_FIPS,
    NULLIF(TRIM("age_group"), '') AS Age_Group,
    NULLIF(TRIM("sex"), '') AS Gender,
    NULLIF(TRIM("race"), '') AS Race,
    NULLIF(TRIM("ethnicity"), '') AS Ethnicity,
    NULLIF(TRIM("case_onset_interval"), '') AS Case_Onset_Interval,
    NULLIF(TRIM("process"), '') AS Process_Type,
    NULLIF(TRIM("exposure_yn"), '') AS Exposure_Status,
    NULLIF(TRIM("current_status"), '') AS Case_Status,
    NULLIF(TRIM("symptom_status"), '') AS Symptom_Status,
    NULLIF(TRIM("hosp_yn"), '') AS Hospitalization_Status,
    NULLIF(TRIM("icu_yn"), '') AS ICU_Status,
    NULLIF(TRIM("death_yn"), '') AS Death_Status,
    NULLIF(TRIM("case_positive_specimen"), '') AS Positive_Specimen_Interval,
    NULLIF(TRIM("underlying_conditions_yn"), '') AS Underlying_Conditions,
    NULLIF(TRIM("unique_key"), '') AS Unique_Key
FROM {{ source('COVID19_DB', 'CDC_RAW_CASES_1') }}