SELECT
    -- Totals and demographics
    CAST(NULLIF(TRIM("TOTAL_POPULATION"), '') AS BIGINT) AS total_population,
    CAST(NULLIF(TRIM("MALE_POPULATION"), '') AS BIGINT) AS male_population,
    CAST(NULLIF(TRIM("FEMALE_POPULATION"), '') AS BIGINT) AS female_population,

    -- Age groups
    CAST(NULLIF(TRIM("UNDER_5_POPULATION"), '') AS BIGINT) AS pop_under_5,
    CAST(NULLIF(TRIM("5_TO_9_POPULATION"), '') AS BIGINT) AS pop_5_to_9,
    CAST(NULLIF(TRIM("10_TO_14_POPULATION"), '') AS BIGINT) AS pop_10_to_14,
    CAST(NULLIF(TRIM("15_TO_19_POPULATION"), '') AS BIGINT) AS pop_15_to_19,
    CAST(NULLIF(TRIM("20_TO_24_POPULATION"), '') AS BIGINT) AS pop_20_to_24,
    CAST(NULLIF(TRIM("25_TO_34_POPULATION"), '') AS BIGINT) AS pop_25_to_34,
    CAST(NULLIF(TRIM("35_TO_44_POPULATION"), '') AS BIGINT) AS pop_35_to_44,
    CAST(NULLIF(TRIM("45_TO_54_POPULATION"), '') AS BIGINT) AS pop_45_to_54,
    CAST(NULLIF(TRIM("55_TO_59_POPULATION"), '') AS BIGINT) AS pop_55_to_59,
    CAST(NULLIF(TRIM("60_TO_64_POPULATION"), '') AS BIGINT) AS pop_60_to_64,
    CAST(NULLIF(TRIM("65_TO_74_POPULATION"), '') AS BIGINT) AS pop_65_to_74,
    CAST(NULLIF(TRIM("75_TO_84_POPULATION"), '') AS BIGINT) AS pop_75_to_84,
    CAST(NULLIF(TRIM("85_PLUS_POPULATION"), '') AS BIGINT) AS pop_85_plus,

    -- Broader age categories
    (
        CAST(NULLIF(TRIM("UNDER_5_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("5_TO_9_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("10_TO_14_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("15_TO_19_POPULATION"), '') AS BIGINT)
    ) AS pop_0_to_19_approx,

    (
        CAST(NULLIF(TRIM("20_TO_24_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("25_TO_34_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("35_TO_44_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("45_TO_54_POPULATION"), '') AS BIGINT)
    ) AS pop_18_to_54_approx,

    (
        CAST(NULLIF(TRIM("55_TO_59_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("60_TO_64_POPULATION"), '') AS BIGINT)
    ) AS pop_50_to_64_approx,

    (
        CAST(NULLIF(TRIM("65_TO_74_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("75_TO_84_POPULATION"), '') AS BIGINT)
        + CAST(NULLIF(TRIM("85_PLUS_POPULATION"), '') AS BIGINT)
    ) AS pop_65_plus,

    -- Race and ethnicity
    CAST(NULLIF(TRIM("WHITE_POPULATION"), '') AS BIGINT) AS pop_white,
    CAST(NULLIF(TRIM("BLACK_OR_AFRICAN_AMERICAN_POPULATION"), '') AS BIGINT) AS pop_black,
    CAST(NULLIF(TRIM("AMERICAN_INDIAN_AND_ALASKA_NATIVE_POPULATION"), '') AS BIGINT) AS pop_amer_indian_ak_native,
    CAST(NULLIF(TRIM("ASIAN_POPULATION"), '') AS BIGINT) AS pop_asian,
    CAST(NULLIF(TRIM("NATIVE_HAWAIIAN_AND_OTHER_PACIFIC_ISLANDER_POPULATION"), '') AS BIGINT) AS pop_hawaiian_pac_islander,
    CAST(NULLIF(TRIM("SOME_OTHER_RACE_POPULATION"), '') AS BIGINT) AS pop_other_race,

    -- Geography
    TRY_CAST(NULLIF(TRIM("STATE"), '') AS INT) AS state_code,
    TRY_CAST(NULLIF(TRIM("COUNTY"), '') AS INT) AS county_code,
    TRY_CAST(NULLIF(TRIM("FIPS_CODE"), '') AS INT) AS fips_code

FROM {{ source('COVID19_DB', 'US_CENSUS_2023') }}