SELECT
    CAST(NULLIF(TRIM("CASE_MONTH"), '') || '-01' AS DATE) AS Case_Month,
    NULLIF(TRIM("RES_STATE"), '') AS Resident_State,
    TRY_CAST(NULLIF(TRIM("STATE_FIPS_CODE"), '') AS INT) AS State_FIPS,
    NULLIF(TRIM("RES_COUNTY"), '') AS Resident_County,
    TRY_CAST(NULLIF(TRIM("COUNTY_FIPS_CODE"), '') AS INT) AS County_FIPS,
    NULLIF(TRIM("AGE_GROUP"), '') AS Age_Group,
    NULLIF(TRIM("SEX"), '') AS Gender,
    NULLIF(TRIM("RACE"), '') AS Race,
    NULLIF(TRIM("ETHNICITY"), '') AS Ethnicity,
    NULLIF(TRIM("CASE_ONSET_INTERVAL"), '') AS Case_Onset_Interval,
    NULLIF(TRIM("PROCESS"), '') AS Process_Type,
    NULLIF(TRIM("EXPOSURE_YN"), '') AS Exposure_Status,
    NULLIF(TRIM("CURRENT_STATUS"), '') AS Case_Status,
    NULLIF(TRIM("SYMPTOM_STATUS"), '') AS Symptom_Status,
    NULLIF(TRIM("HOSP_YN"), '') AS Hospitalization_Status,
    NULLIF(TRIM("ICU_YN"), '') AS ICU_Status,
    NULLIF(TRIM("DEATH_YN"), '') AS Death_Status,
    NULLIF(TRIM("CASE_POSITIVE_SPECIMEN"), '') AS Positive_Specimen_Interval,
    NULLIF(TRIM("UNDERLYING_CONDITIONS_YN"), '') AS Underlying_Conditions,
    NULLIF(TRIM("UNIQUE_KEY"), '') AS Unique_Key
FROM {{ source('COVID19_DB', 'CDC_RAW_CASES_1') }}