WITH monthly_cases AS (
    SELECT
        CASE_MONTH,
        RESIDENT_STATE,
        COUNT(*) AS TOTAL_RECORDED_CASES,
        COUNT(CASE WHEN DEATH_STATUS = 'Yes' THEN 1 END) AS DEATH_COUNT,
        COUNT(CASE WHEN HOSPITALIZATION_STATUS = 'Yes' THEN 1 END) AS HOSPITALIZATION_COUNT
    FROM {{ ref('stg_cdc_cases') }}
    WHERE CASE_MONTH IS NOT NULL
      AND RESIDENT_STATE IS NOT NULL
    GROUP BY CASE_MONTH, RESIDENT_STATE
)
SELECT
    CASE_MONTH,
    RESIDENT_STATE,
    TOTAL_RECORDED_CASES,
    DEATH_COUNT,
    HOSPITALIZATION_COUNT,
    AVG(TOTAL_RECORDED_CASES) OVER (
        PARTITION BY RESIDENT_STATE
        ORDER BY CASE_MONTH
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS CASES_3_MONTH_ROLLING_AVG,
    AVG(DEATH_COUNT) OVER (
        PARTITION BY RESIDENT_STATE
        ORDER BY CASE_MONTH
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS DEATHS_3_MONTH_ROLLING_AVG,
    AVG(HOSPITALIZATION_COUNT) OVER (
        PARTITION BY RESIDENT_STATE
        ORDER BY CASE_MONTH
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS HOSPITALIZATIONS_3_MONTH_ROLLING_AVG
FROM monthly_cases
ORDER BY CASE_MONTH, RESIDENT_STATE