WITH cases_by_state AS (
    SELECT
        RESIDENT_STATE,
        STATE_FIPS,
        COUNT(*) AS TOTAL_RECORDED_CASES,
        COUNT(CASE WHEN DEATH_STATUS = 'Yes' THEN 1 END) AS DEATH_COUNT,
        COUNT(CASE WHEN HOSPITALIZATION_STATUS = 'Yes' THEN 1 END) AS HOSPITALIZATION_COUNT
    FROM {{ ref('stg_cdc_cases') }}
    WHERE RESIDENT_STATE IS NOT NULL
      AND STATE_FIPS IS NOT NULL
    GROUP BY RESIDENT_STATE, STATE_FIPS
),
population_by_state AS (
    SELECT
        STATE_CODE AS STATE_FIPS,
        SUM(TOTAL_POPULATION) AS TOTAL_POPULATION
    FROM {{ ref('stg_census') }}
    WHERE STATE_CODE IS NOT NULL
    GROUP BY STATE_CODE
)
SELECT
    c.RESIDENT_STATE,
    c.STATE_FIPS,
    p.TOTAL_POPULATION,
    c.TOTAL_RECORDED_CASES,
    c.DEATH_COUNT,
    c.HOSPITALIZATION_COUNT,
    ROUND((c.TOTAL_RECORDED_CASES * 100000.0) / NULLIF(p.TOTAL_POPULATION, 0), 2) AS CASES_PER_100K,
    ROUND((c.DEATH_COUNT * 100000.0) / NULLIF(p.TOTAL_POPULATION, 0), 2) AS DEATHS_PER_100K,
    ROUND((c.HOSPITALIZATION_COUNT * 100000.0) / NULLIF(p.TOTAL_POPULATION, 0), 2) AS HOSPITALIZATIONS_PER_100K
FROM cases_by_state c
LEFT JOIN population_by_state p
    ON c.STATE_FIPS = p.STATE_FIPS
ORDER BY CASES_PER_100K DESC