WITH source_stats AS (
    SELECT
        'CDC_RAW_CASES_1' AS SOURCE_NAME,
        MAX(CAST(CASE_MONTH AS DATE)) AS LATEST_BUSINESS_DATE,
        COUNT(*) AS ROW_COUNT
    FROM {{ ref('stg_cdc_cases') }}

    UNION ALL

    SELECT
        'US_CENSUS_2023' AS SOURCE_NAME,
        NULL AS LATEST_BUSINESS_DATE,
        COUNT(*) AS ROW_COUNT
    FROM {{ ref('stg_census') }}
),
table_metadata AS (
    SELECT
        TABLE_NAME,
        LAST_ALTERED
    FROM {{ target.database }}.INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'BRONZE'
      AND TABLE_NAME IN ('CDC_RAW_CASES_1', 'US_CENSUS_2023')
)
SELECT
    s.SOURCE_NAME,
    s.ROW_COUNT,
    s.LATEST_BUSINESS_DATE,
    m.LAST_ALTERED AS LAST_REFRESHED_AT,
    CASE
        WHEN s.LATEST_BUSINESS_DATE IS NULL THEN NULL
        ELSE DATEDIFF('day', s.LATEST_BUSINESS_DATE, CURRENT_DATE)
    END AS DAYS_SINCE_LATEST_BUSINESS_DATE,
    DATEDIFF('hour', m.LAST_ALTERED, CURRENT_TIMESTAMP) AS HOURS_SINCE_LAST_REFRESH
FROM source_stats s
LEFT JOIN table_metadata m
    ON s.SOURCE_NAME = m.TABLE_NAME
ORDER BY SOURCE_NAME